### ISSUE TITLE
Freedv Reporter (not web) starts to duplicate and triplicate users after a long session. 

### ISSUE THREAD

**Issue by barjac** [drowe67/freedv-gui#464]
This applies to a build of ms-preserve-reporter-layout branch yesterday.
After about an hour in QSO with two other stations I began to notice that I and the other stations were appearing twice and then three times in the list.
After signing I closed and restarted the reporter and the excess entries cleared.
Could this be a feature to preserve reporting for all members of the group? I doubt it since I was seeing lots of other stations duplicated.

**Comment by tmiw** [comment]
I wonder if it was some sort of temporary network glitch on the server side or somewhere between it and you. It might be worth pinging qso.freedv.org and seeing if there are any dropouts when this happens.

Anyway, if it's operating correctly the duplicates should drop off on their own within a minute or so if it is indeed some sort of network glitch. Let me know if that's not actually happening.

**Comment by barjac** [comment]
I will build master and test again during the net later today.
When I noticed this it was there for much longer than a few minutes, so it did not seem to be clearing itself, only when I finally killed the reporter and restarted it were all the many duplicates removed.
I have been suffering with occasional slow www speeds recently, not sure about during the OSO, but there was nothing else apparent in the reporter. Everyones TX was indicated instantly and SNRs were being updated OK.
Remember that I was using a ms-preserve-reporter-layout branch build if this is relevant.

**Comment by barjac** [comment]
Current master in QSO now:
![Screenshot_20230710_160632](https://github.com/drowe67/freedv-gui/assets/1324702/228ce46f-c146-442e-80f1-4253a87e0dc4)

**Comment by barjac** [comment]
Now there are 3 of me!

![Screenshot_20230710_161537](https://github.com/drowe67/freedv-gui/assets/1324702/37e2ea90-972d-47a7-a130-3688a55f02d6)

**Comment by barjac** [comment]
And this is at the end of the 1 hour net.

![Screenshot_20230710_170115](https://github.com/drowe67/freedv-gui/assets/1324702/54cb9f06-0eaa-4219-8f10-ce42064e530f)

**Comment by tmiw** [comment]
OK, I think I misunderstood what was happening. I thought this was something that was happening on the website, too.

Anyway, I was able to reproduce the issue by pushing Start and disabling IPv6 on my laptop afterward (to force a reconnect onto IPv4). #468 should fix it; turns out the socket.io client doesn't call close and open when reconnecting, just the "reconnect" event--so the necessary GUI event handlers to kick off the refresh weren't firing.

> Something I have noticed is that I am now seeing 0.0 dB appear in the SNR column when the Last Rx and Mode columns are blank, i.e. the unknown entry disappears in 2 out of 3 columns.
> 
> The 0.0dB thing seems to happen at the first frequency change or update for a new entry, but it always happens very quickly for the local user.

Yeah, this is a side effect of a change I made on the server the other day per @barjac's request. Before, the RX columns were showing the last received in the entire session, which may be confusing to users if someone changes frequency. Now when the server detects a frequency change, it sends an RX event with callsign and mode blanked out to clear that info. I had implemented blanking out of the SNR on the website but not on the app yet. 

Anyway, https://github.com/drowe67/freedv-gui/pull/462/commits/a8d2e61f25c29d269f4fc0e47319353f7f9365ad has the fix for that too.

**Comment by barjac** [comment]
This is still happening. Please re-open.

Today I left FreeDV running (on my desktop x86_64) for most of the day and ended up with pages and pages of duplicates. Around 3 full screens of reporter (all bands) when there were actually only half a screen.

Stopping the reporter and re-starting it made no difference and neither did stopping and re-starting the modem.

All this time I had the RPi4b (aarch64) running in receive only and the reporter there did not show any signs of doing this.

Both machines are connected to the same LAN x86_64 via ethernet), RPi4b via wi-fi.

Stopping the main program and re-starting it finally cleared all the duplicates.

Some of the duplicate lines were for stations that had shut down hours previously. Some were for stations that had changed band and were being shown for both bands.

The RPi4b which was running the whole time agreed with the web reporter.

I also saw one station shown reporting RX of different stations on different lines. There were several of these.

All very strange.

**Comment by tmiw** [comment]
BTW I fixed a bug related to band tracking tonight. I don't know if that impacts this issue at all but since that's in master now, it's worth a shot.

**Comment by barjac** [comment]
Sorry that I have not had time to test much for the last week as my wife is in hospital.
I will do what I can as and when. :(

**Comment by tmiw** [comment]
I'm sorry to hear about your wife :( No rush, just whenever you can.

**Comment by barjac** [comment]
> I'm sorry to hear about your wife :( No rush, just whenever you can.

I was just playing around with the 'PTT Uses:' thing while running a second 'monitor' system with different settings to test how the reporter behaved.

At the end of this I noticed the reporter was showing several stations multiple times. Is it intentional that 'old' reporting of a station remains in the list after they have changed band or switched from RX only to TX/RX?
This is maybe what is happening.

The shot below was showing me (from around 16.40 UTC when I started) as 'RX only' even after that system was shut down, and the G0TFD entries are interesting, it helps to be able to sort on callsign.

![Screenshot_20230926_181906](https://github.com/drowe67/freedv-gui/assets/1324702/3745aaa8-74d6-4c9d-802f-09f720f103fc)

**Comment by tmiw** [comment]
> At the end of this I noticed the reporter was showing several stations multiple times. Is it intentional that 'old' reporting of a station remains in the list after they have changed band or switched from RX only to TX/RX? This is maybe what is happening.

There shouldn't be new entries getting created when people change bands. To confirm, this is only on the in-app one and not the Web based one, correct?

Regardless, I pushed a config change on the server side to hopefully recycle disconnected users more quickly. I don't know if that will help for you, though, especially if the Web version still looks okay.

**Comment by barjac** [comment]
This is only the internal reporter.
I will continue to test in order to maybe find a way to reproduce.
So far I have not actually witnessed this actually as it happens more often I am filtering a specific band and it is only when I later view 'All bands' that I notice this has happened.

**Comment by barjac** [comment]
This is from my RX only monitor RPi this afternoon, it was left untouched from a clean boot while monitoring an SDR on 60m. The display was set to track the main radio connected to another machine, so I was not watching all bands. This is what I just found after turning the tracking off:

![screen](https://github.com/drowe67/freedv-gui/assets/1324702/8a9dee42-3561-4f8e-967e-7a86c5ab8635)

**Comment by Tyrbiter** [comment]
It would seem to be related to the tracking feature, I use that quite rarely and I only recall one occasion when I saw a callsign in the list more than once.

**Comment by tmiw** [comment]
> It would seem to be related to the tracking feature, I use that quite rarely and I only recall one occasion when I saw a callsign in the list more than once.

Actually, filtering in general. It's just that the tracking may be making it more likely to happen.

More info at this PR, which hopefully will fix the issue: https://github.com/drowe67/freedv-gui/pull/557 (Discovered by reviewing the code; haven't been able to duplicate but based on the fix would probably have been straightforward to do had I been connected long enough.)

**Comment by Tyrbiter** [comment]
Ah, that's interesting, I did see the duplication with filtering enabled but not tracking.

New PR now installed here for testing.

**Comment by barjac** [comment]
I never know whether to comment in the bug or the PR. My comments are in the PR which appears to work.

**Comment by tmiw** [comment]
Either is fine :)
